Repository 2025KAU-MAITE/FE, pull requests merged in 2025-05, with the labels that each got.

#18 Fix/AndroidManifest 문제 해결 완료
  app/build.gradle.kts
  app/src/main/res/drawable/img_profile_dummy.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#25 Design: 수정 달력 디자인, Fix: 수정 자잘한 버그들
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/maite/ListDetailFragment.kt
  app/src/main/res/drawable/timetable_cell_border.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: bug, enhancement

#32 Feature/create maite
  app/src/main/java/com/example/maite/CreateMaiteBottomSheet.kt
  app/src/main/java/com/example/maite/InviteBottomSheet.kt
  app/src/main/java/com/example/maite/view/ListFragment.kt
  app/src/main/res/layout/bottom_sheet_create_maite.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#35 Feature/suggested meet list
  app/src/main/java/com/example/maite/ListDetailFragment.kt
  app/src/main/java/com/example/maite/model/MaiteListRepository.kt
  app/src/main/java/com/example/maite/model/MeetListRepository.kt
  app/src/main/java/com/example/maite/model/PropMeetItem.kt
  app/src/main/java/com/example/maite/model/PropMeetRepository.kt
  app/src/main/java/com/example/maite/view/PropMeetAdapter.kt
  app/src/main/java/com/example/maite/view/PropMeetFragment.kt
  app/src/main/java/com/example/maite/viewmodel/MaiteListViewModel.kt
  app/src/main/java/com/example/maite/viewmodel/MeetListViewModel.kt
  app/src/main/java/com/example/maite/viewmodel/PropMeetViewModel.kt
  app/src/main/res/layout/fragment_prop_meet.xml
  app/src/main/res/layout/item_prop_meet.xml
Labels: enhancement

#36 feat: 회원가입, 로그인 API 연결
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/assets/daum_address.html
  app/src/main/java/com/example/maite/ApiClient.kt
  app/src/main/java/com/example/maite/model/AuthApi.kt
  app/src/main/java/com/example/maite/model/EmailCheckModels.kt
  app/src/main/java/com/example/maite/model/LoginRequest.kt
  app/src/main/java/com/example/maite/model/LoginResponse.kt
  app/src/main/java/com/example/maite/model/SignupDataHolder.kt
  app/src/main/java/com/example/maite/model/SignupRequest.kt
  app/src/main/java/com/example/maite/model/SignupResponse.kt
  app/src/main/java/com/example/maite/model/SmsAuthModels.kt
  app/src/main/java/com/example/maite/repository/AuthRepository.kt
  app/src/main/java/com/example/maite/view/LoginActivity.kt
  app/src/main/java/com/example/maite/view/SignupAddressFragment.kt
  app/src/main/java/com/example/maite/view/SignupCompletionFragment.kt
  app/src/main/java/com/example/maite/view/SignupFragment.kt
  app/src/main/java/com/example/maite/view/SignupProfileFragment.kt
  app/src/main/java/com/example/maite/view/SignupProfilePictureFragment.kt
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/fragment_signup_address.xml
  app/src/main/res/layout/fragment_signup_completion.xml
  app/src/main/res/layout/fragment_signup_profile.xml
Labels: enhancement

#38 fix: 버그 해결 완료
  app/build.gradle.kts
  gradlew
Labels: bug

#40 feat: 검색 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/example/maite/SearchFragment.kt
  app/src/main/java/com/example/maite/adapter/SearchAdapter.kt
  app/src/main/java/com/example/maite/api/UserApiService.kt
  app/src/main/java/com/example/maite/model/User.kt
  app/src/main/java/com/example/maite/repository/UserRepository.kt
  app/src/main/java/com/example/maite/viewmodel/SearchViewModel.kt
  app/src/main/java/com/example/maite/viewmodel/SearchViewModelFactory.kt
  app/src/main/res/drawable/ic_person_placeholder.xml
  app/src/main/res/drawable/rounded_button_background.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search_result.xml
Labels: enhancement

#41 Feature/upload record
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/maite/LoadingDialog.kt
  app/src/main/java/com/example/maite/MaiteApiService.kt
  app/src/main/java/com/example/maite/MaiteRetrofitClient.kt
  app/src/main/java/com/example/maite/MeetDetailFragment.kt
  app/src/main/java/com/example/maite/UploadBottomSheet.kt
  app/src/main/res/drawable/ic_upload.xml
  app/src/main/res/layout/bottom_sheet_upload.xml
  app/src/main/res/layout/fragment_meet_detail.xml
  app/src/main/res/layout/loading_dialog.xml
Labels: enhancement

#45 fix: 인증번호 못받는 버그 해결
  app/src/main/java/com/example/maite/model/SmsAuthModels.kt
  app/src/main/java/com/example/maite/repository/AuthRepository.kt
Labels: bug

#52 fix: 로그인 안되는 문제 해결
  app/src/main/java/com/example/maite/ApiClient.kt
  app/src/main/java/com/example/maite/AuthInterceptor.kt
  app/src/main/java/com/example/maite/view/LoginActivity.kt
Labels: bug

#63 fix: 시간표 조회 이슈 해결 완료
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/maite/HomeFragment.kt
  app/src/main/java/com/example/maite/api/TimetableApi.kt
  app/src/main/java/com/example/maite/repository/TimetableRepository.kt
  app/src/main/java/com/example/maite/ui/profile/EditTimetableFragment.kt
  app/src/main/java/com/example/maite/ui/profile/ProfileViewModel.kt
Labels: bug

#68 Fix/홈 제안 안뜨는 이슈 해결
  .gitignore
  app/src/main/java/com/example/maite/HomeFragment.kt
  app/src/main/java/com/example/maite/MainActivity.kt
  app/src/main/java/com/example/maite/PreferencesUtil.kt
  app/src/main/java/com/example/maite/api/ProposalApi.kt
  app/src/main/java/com/example/maite/data/mapper/ProposalMapper.kt
  app/src/main/java/com/example/maite/data/model/ProposalResponse.kt
  app/src/main/java/com/example/maite/data/repository/ProposalRepository.kt
  app/src/main/java/com/example/maite/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/maite/view/ListFragment.kt
Labels: bug

#75 Design: 추가 채팅 목록 UI, Feat: 추가 채팅 목록
  app/src/main/java/com/example/maite/ChatListFragment.kt
  app/src/main/java/com/example/maite/HomeFragment.kt
  app/src/main/java/com/example/maite/model/ChatListItem.kt
  app/src/main/java/com/example/maite/model/ChatListRepository.kt
  app/src/main/java/com/example/maite/view/ChatListAdapter.kt
  app/src/main/java/com/example/maite/viewmodel/ChatListViewModel.kt
  app/src/main/res/layout/fragment_chat_list.xml
  app/src/main/res/layout/item_chat_maite.xml
  app/src/main/res/layout/item_chat_personal.xml
Labels: enhancement

#78 feat: 구글 로그인 연동 (추후 작업 재개)
  .idea/.name
  .idea/deploymentTargetSelector.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/java/com/example/maite/model/AuthApi.kt
  app/src/main/java/com/example/maite/model/GoogleLoginRequest.kt
  app/src/main/java/com/example/maite/model/SocialSignupRequest.kt
  app/src/main/java/com/example/maite/repository/AuthRepository.kt
  app/src/main/java/com/example/maite/view/LoginActivity.kt
  app/src/main/java/com/example/maite/view/SignupCompletionFragment.kt
  app/src/main/java/com/example/maite/viewmodel/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_social_signup.xml
  app/src/main/res/values/auth_strings.xml
Labels: enhancement

#84 Design: 추가 AI 호출, Feat: 추가 AI 호출
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/maite/AiDialog.kt
  app/src/main/java/com/example/maite/MeetDetailFragment.kt
  app/src/main/res/drawable/btn_ai.xml
  app/src/main/res/drawable/tooltip_background.xml
  app/src/main/res/layout/ai_dialog.xml
  app/src/main/res/layout/fragment_meet_detail.xml
Labels: enhancement

#85 feat: 비밀번호 찾기 및 재설정 구현
  app/src/main/java/com/example/maite/AuthInterceptor.kt
  app/src/main/java/com/example/maite/model/AuthApi.kt
  app/src/main/java/com/example/maite/model/ResetPasswordModel.kt
  app/src/main/java/com/example/maite/repository/AuthRepository.kt
  app/src/main/java/com/example/maite/util/PasswordResetDataHolder.kt
  app/src/main/java/com/example/maite/view/FindPasswordFragment.kt
  app/src/main/java/com/example/maite/view/UpdatePasswordFragment.kt
  app/src/main/res/layout/fragment_find_password.xml
  app/src/main/res/layout/fragment_update_password.xml
Labels: enhancement

#88 Feature/maite timetable
  app/src/main/java/com/example/maite/ListDetailFragment.kt
  app/src/main/java/com/example/maite/MaiteApiService.kt
  app/src/main/java/com/example/maite/RoomTimetableResponse.kt
  app/src/main/java/com/example/maite/RoomTimetableUtils.kt
Labels: enhancement

#91 Fix/maite timetable click
  app/src/main/java/com/example/maite/ListDetailFragment.kt
Labels: bug, enhancement

#99 feat: 설정 화면 구현
  app/src/main/java/com/example/maite/ProfileFragment.kt
  app/src/main/java/com/example/maite/model/AuthApi.kt
  app/src/main/java/com/example/maite/ui/settings/SettingsFragment.kt
  app/src/main/java/com/example/maite/ui/subscription/SubscriptionFragment.kt
  app/src/main/java/com/example/maite/view/LoginActivity.kt
  app/src/main/res/drawable/bg_arrow_button.xml
  app/src/main/res/drawable/bg_blue_border.xml
  app/src/main/res/drawable/bg_blue_circle.xml
  app/src/main/res/drawable/bg_button_gray.xml
  app/src/main/res/drawable/bg_gray_edit_text.xml
  app/src/main/res/drawable/bg_plan_badge.xml
  app/src/main/res/drawable/bg_settings_item.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_subscription.xml
Labels: enhancement

#105 feat: 구독제
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/maite/PreferencesUtil.kt
  app/src/main/java/com/example/maite/ProfileFragment.kt
  app/src/main/java/com/example/maite/SearchFragment.kt
  app/src/main/java/com/example/maite/UserInfoResponse.kt
  app/src/main/java/com/example/maite/adapter/SearchAdapter.kt
  app/src/main/java/com/example/maite/api/KakaoPayApi.kt
  app/src/main/java/com/example/maite/api/UserApiService.kt
  app/src/main/java/com/example/maite/model/KakaoPayRequest.kt
  app/src/main/java/com/example/maite/model/UserInfo.kt
  app/src/main/java/com/example/maite/repository/PaymentRepository.kt
  app/src/main/java/com/example/maite/repository/SearchUserRepository.kt
  app/src/main/java/com/example/maite/repository/UserRepository.kt
  app/src/main/java/com/example/maite/ui/payment/KakaoPayWebViewActivity.kt
  app/src/main/java/com/example/maite/ui/settings/SettingsFragment.kt
  app/src/main/java/com/example/maite/ui/subscription/SubscriptionFragment.kt
  app/src/main/java/com/example/maite/view/LoginActivity.kt
  app/src/main/java/com/example/maite/viewmodel/SearchViewModel.kt
  app/src/main/res/drawable/bg_button_main.xml
  app/src/main/res/drawable/bg_premium_badge.xml
  app/src/main/res/drawable/bg_student_discount_info.xml
  app/src/main/res/drawable/btn_bottom_active.xml
  app/src/main/res/layout/activity_kakao_pay_web_view.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_subscription.xml
Labels: enhancement

#108 feat: 회원가입시 프로필 사진 업로드 기능 추가
  app/src/main/java/com/example/maite/model/AuthApi.kt
  app/src/main/java/com/example/maite/repository/UserRepository.kt
  app/src/main/java/com/example/maite/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/example/maite/view/SignupProfilePictureFragment.kt
  app/src/main/res/layout/fragment_signup_profile_picture.xml
Labels: enhancement

#110 feature: 스플래시 이미지 추가
  .gitignore
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/maite/view/LoginActivity.kt
  app/src/main/java/com/example/maite/view/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_subscription.xml
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/themes.xml
Labels: enhancement
